import { Platform } from 'react-native'
import { colors } from 'components/ui/tokens'

export const styles = {
  header: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: Platform.OS === 'ios' ? 60 : 40,
    backgroundColor: colors.warmSurface,
    borderBottomWidth: 1,
    borderBottomColor: colors.warmBorder,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.warmBorderStrong,
    backgroundColor: colors.warmSurface,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  headerTitle: {
    fontFamily: 'Syne_700Bold',
    fontSize: 18,
    color: colors.ink,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: colors.warmBg,
  },
  userSection: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: 12,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.warmBorder,
  },
  userInfoCol: {
    flex: 1,
    justifyContent: 'center' as const,
  },
  userName: {
    fontFamily: 'Poppins_600SemiBold',
    fontSize: 15,
    color: colors.ink,
  },
  userSubtitle: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 12.5,
    color: colors.mute,
    marginTop: 2,
  },
  avatarCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primaryDeep2,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    overflow: 'hidden' as const,
  },
  avatarInitials: {
    fontFamily: 'Poppins_700Bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  textInputSection: {
    paddingVertical: 20,
    position: 'relative' as const,
  },
  textInput: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 16,
    lineHeight: 24,
    color: colors.ink,
    minHeight: 120,
    maxHeight: 200,
    backgroundColor: 'transparent',
    borderWidth: 0,
    paddingBottom: 30,
  },
  characterCounter: {
    position: 'absolute' as const,
    bottom: 8,
    right: 8,
    backgroundColor: colors.warmSurface,
    borderWidth: 1,
    borderColor: colors.warmBorder,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  counterText: {
    fontFamily: 'Poppins_500Medium',
    fontSize: 12,
    color: colors.mute,
  },
  counterWarning: {
    color: colors.coral,
  },
  quickActions: {
    flexDirection: 'row' as const,
    justifyContent: 'flex-start' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.warmBorder,
    marginTop: 20,
  },
  actionButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: colors.warmSurface,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: colors.warmBorderStrong,
  },
  actionText: {
    marginLeft: 6,
    fontFamily: 'Poppins_500Medium',
    fontSize: 13,
    color: colors.soft,
  },
  bottomSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
  },
  bottomSheetHandle: {
    backgroundColor: colors.warmBorderStrong,
    width: 40,
    height: 4,
    borderRadius: 2,
  },
  bottomSheetBackground: {
    backgroundColor: colors.warmSurface,
  },
  bottomSheetContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  loadingOverlay: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(245, 243, 238, 0.92)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    zIndex: 1000,
  },
  loadingContent: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    padding: 32,
    backgroundColor: colors.warmSurface,
    borderWidth: 1,
    borderColor: colors.warmBorder,
    borderRadius: 16,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  loadingIcon: {
    marginBottom: 16,
  },
  loadingText: {
    fontFamily: 'Syne_700Bold',
    fontSize: 18,
    color: colors.ink,
    marginBottom: 8,
    textAlign: 'center' as const,
  },
  loadingSubtext: {
    fontFamily: 'Poppins_400Regular',
    fontSize: 14,
    color: colors.soft,
    textAlign: 'center' as const,
    lineHeight: 20,
  },
}
